### ISSUE TITLE
Compilation error when option WITH_TOOLS is enabled

### ISSUE THREAD

**Issue by undef21** [ihhub/fheroes2#2013]
This regression is introduced from #1993 
Tools depend on Surface::DrawPoint, Surface::SetPixel{,1,2,3,4,24}

**Comment by ihhub** [comment]
`tools` are very outdated as the algorithm used there is incorrect.

**Comment by ihhub** [comment]
Hi @undef21 , we're going to make needed changes in `image_tool.h` and `image_tool.cpp` to add the code for saving images. Currently we can save the internal Image type. Next thing is to move the code from `agg.cpp` to **image_tool** to convert ICN into Image.

After these changes the code from tools will be greatly simplified and compilation will be succeeded. Also I agree that we need to include tools into Unix compilation.
